In [44]:
import pandas as pd

holdings = pd.read_excel("Portfolio.xlsx", 
                         sheet_name="DVF Tracker",
                         header=2, ## headers are row 3
                         usecols="C:L", ## ticker through total gain.
                         nrows=17,)

## % of portfolio
holdings["Weight"] = (holdings["Market Value"] / holdings["Market Value"].sum()*100)
holdings[["Ticker", "Shares", "Market Value", "Weight"]]

   Ticker  Shares  Market Value     Weight
0    ASTS    1100   102734.5000   5.905610
1    BKNG     300    49269.0000   2.832189
2     BLK      70    69843.9000   4.014920
3     COP     650    77181.0000   4.436687
4     DSI    3340   470606.0000  27.052405
5    GOOG     400   143856.0000   8.269446
6    MSFT     165    67785.3165   3.896584
7     NKE     850    36885.7500   2.120347
8    NVDA     600   125442.0000   7.210932
9      PG     320    46518.4000   2.674073
10   PYPL     940    38732.7000   2.226518
11    RTX     625   111865.6250   6.430505
12      V     180    57611.7000   3.311762
13   META     130    76491.0250   4.397025
14   ORCL     480   102604.8000   5.898154
15    APH     560    80444.0000   4.624258
16   COST      84    81737.0400   4.698588

## DSI @ 27% of the fund. 
its a benchmark ESG ETF: leaving 73% throughout 16 single stocks. 
should we measure gaps with DSI included or excluded?

In [45]:
## Sector map and weights

sector_map = {
    "NVDA"  : "Technology",
    "ASTS"  : "Technology",
    "MSFT"  : "Technology",
    "ORCL"  : "Technology",
    "APH"   : "Technology",

    "GOOG"  : "Communication Services",
    "META"  : "Communication Services",

    "RTX"   : "Industrials",

    "COP"   : "Energy",

    "BLK"   : "Financial Services",
    "V"     : "Financial Services",
    "PYPL"  : "Financial Services",

    "BKNG"  : "Consumer Cyclical",
    "NKE"   : "Consumer Cyclical",

    "PG"    : "Consumer Defensive",
    "COST"  : "Consumer Defensive",

    "DSI"   : "ETF",
}

holdings["Sector"] = holdings["Ticker"].map(sector_map)

sector_weights = (
    holdings.groupby("Sector")["Weight"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)
sector_weights

                   Sector     Weight
0              Technology  27.535537
1                     ETF  27.052405
2  Communication Services  12.666470
3      Financial Services   9.553200
4      Consumer Defensive   7.372660
5             Industrials   6.430505
6       Consumer Cyclical   4.952536
7                  Energy   4.436687

## Missing Sectors
### Sectors missing from the portfolio are: 
- Healthcare
- Utilities
- Real Estate
- Basic Materials

We should look to target these sectors with the aim of further diversifying the portfolio.
as shown in Wednesday's meeting, the diversified investors are safest, and most succesfull long term.

Hello, from AJ